# Generated by Django 5.2.14 on 2026-06-16 23:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('whatax', '0007_moon_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Signed: + credit (reduces owed), − debit.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanceadjustment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extractionore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='miningledgerentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='miningledgerentry',
            name='recorded_date',
            field=models.DateField(help_text='Observer last_updated (a date).'),
        ),
        migrations.AlterField(
            model_name='miningsnapshot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='miningsnapshot',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='Mining counted but not taxed (sec-class / structure exclusion).'),
        ),
        migrations.AlterField(
            model_name='miningstructure',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False excludes this structure's mining from tax."),
        ),
        migrations.AlterField(
            model_name='miningstructure',
            name='structure_id',
            field=models.BigIntegerField(help_text='ESI structure id; doubles as observer_id.', unique=True),
        ),
        migrations.AlterField(
            model_name='moonextraction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moonextraction',
            name='total_good_ore_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dead-% denominator; NULL = composition unknown.', max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='character_id',
            field=models.BigIntegerField(blank=True, help_text='Resolved payer (= first_party_id).', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='Global rate; per-corp overrides win.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Pay-by window after emission before overdue.'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Master kill-switch for scheduled work.'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='janice_api_key',
            field=models.CharField(blank=True, help_text='Stored in DB; never rendered back (§5.1).', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='mineral_price_basis',
            field=models.CharField(choices=[('split_immediate', 'Jita split (immediate)'), ('buy_immediate', 'Jita buy (immediate)'), ('sell_immediate', 'Jita sell (immediate)'), ('split_top5', 'Jita split (top 5% average)'), ('buy_top5', 'Jita buy (top 5% average)'), ('sell_top5', 'Jita sell (top 5% average)')], default='split_immediate', help_text='Which Janice market figure values minerals.', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='payment_corporation',
            field=models.ForeignKey(blank=True, help_text='Corp players pay to; its wallet is monitored.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='eveonline.evecorporationinfo'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='payment_wallet_division',
            field=models.PositiveSmallIntegerField(default=1, help_text='1–7.'),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='reprocessing_yield',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.906'), help_text='Refined-value efficiency factor, e.g. 0.906.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='tax_edit_window_days',
            field=models.PositiveSmallIntegerField(default=15, help_text='Days after emission during which staff may edit tax_due.'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Σ matched payments.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='original_tax_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Immutable audit baseline at emission (post-discount).', max_digits=20),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Effective charge (may differ after a staff edit).', max_digits=20),
        ),
        migrations.AlterField(
            model_name='taxrecordedit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='walletjournalentry',
            name='entry_id',
            field=models.BigIntegerField(help_text='ESI journal id (primary idempotency key).', unique=True),
        ),
        migrations.AlterField(
            model_name='walletjournalentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
